spring:
  # Postgres Database
  datasource:
    url: jdbc:postgresql://localhost:5432/studyalarmpush
    username: dong
    password: dong
    driver-class-name: org.postgresql.Driver
  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8081

########################################################################################################################

#url git 커밋 잘 숨기기
webhook:
  slack:
    url: https://hooks.slack.com/services/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